# Page settings

baseURL = "http://www.colinbut.com/online-resume/"
languageCode = "en"
title = "Colin But online Resume"
theme = "hugo-devresume-theme"
googleAnalytics = "UA-XXXXXXX-Y"






[params]
    author = "CowboySmall"
    description = "DevResume - Bootstrap 4 Resume/CV Template For Software Developers"


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "Colin But"
        tagline = "AWS Cloud / DevOps Engineer"
        avatar = "avatar.png"







    [params.contact]
        enable = true
        location = "London"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "07588818156"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "colin.but1@hotmail.co.uk"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "#"
        text = "www.colinbut.com"







    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "AWS Cloud"
        [[params.skills.list.items]]
        details = "Jenkins CI/CD Pipelines"
        [[params.skills.list.items]]
        details = "Terraform/Cloudformation"
        [[params.skills.list.items]]
        details = "Docker/Kubernetes"
        [[params.skills.list.items]]
        details = "Ansible"
        [[params.skills.list.items]]
        details = "Java/Python/JavaScript/React"
        

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        [[params.skills.list.items]]
        details = "Good time management"








    [params.education]
        enable = true

        [[params.education.list]]
        degree = "MEng in Computer Science"
        university = "University of Strathclyde, Glasgow"
        dates = "2010 - 2011"
        [[params.education.list]]
        degree = "BSc Computer Science"
        university = "University of Strathclyde, Glasgow"
        dates = "2006 - 2010"








    [params.awards]
        enable = true

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"








    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "English"
        level = "Native"
        [[params.languages.list]]
        name = "Chinese (Cantonese)"
        level = "Native"








    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Football"
        [[params.interests.list]]
        name = "Food"
        [[params.interests.list]]
        name = "Gaming"
        [[params.interests.list]]
        name = "Sightseeing"








    [params.summary]
        enable = true
        text = "A Senior Software/DevOps Engineer who specialises working on the AWS cloud with a strong varied development background in both backend + frontend. With a broad technical experience accumulated to date allowed me to apply my range of technical skills across numerous business domains.

A Developer turned DevOps Engineer who is passionate about Infrastructure as Code, creating Pipeline as Code and a firm believer in close collaboration between Developers & Operators aiming to help bridge the gap and shorten the overall release cycle.

An effective team member who is very hands-on and takes ownership of business & technical requirements taking them from concept right through to production."








    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "DevOps Engineer"
        dates = "2019 - Present"
        company = "Credit Agricole, Corporate & Investment Bank"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis."
        [[params.experience.list.items]]
        details = "Lorem ipsum dolor sit amet, consectetuer."
        [[params.experience.list.items]]
        details = "Aenean commodo ligula eget dolor."
        [[params.experience.list.items]]
        details = "Etiam ultricies nisi vel augue."

        [[params.experience.list]]
        title = "Java Developer / DevOps Engineer"
        dates = "2018 - 2019"
        company = "10x Banking"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel."
        [[params.experience.list.items]]
        details = "Lorem ipsum dolor sit amet, consectetuer."
        [[params.experience.list.items]]
        details = "Aenean commodo ligula eget dolor."

        [[params.experience.list]]
        title = "Software Consultant"
        dates = "2018 - 2019"
        company = "OpenCredo"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.experience.list]]
        title = "Java Developer"
        dates = "2016 - 2018"
        company = "Gamesys"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."

        [[params.experience.list]]
        title = "Backend Developer"
        dates = "2015 - 2016"
        company = "Solarcentury"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.experience.list]]
        title = "Software Engineer"
        dates = "2014 - 2015"
        company = "NHS Digital"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."

        [[params.experience.list]]
        title = "Software Engineer"
        dates = "2014 - 2014"
        company = "NHS Digital"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."

        [[params.experience.list]]
        title = "Software Engineer"
        dates = "2011 - 2014"
        company = "Thomson Reuters"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."

        [[params.experience.list]]
        title = "Software Engineer"
        dates = "2011 - 2014"
        company = "Bjss"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."

        [[params.experience.list]]
        title = "Web Developer"
        dates = "2010 - 2011"
        company = "Mobile Velocity"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."

        [[params.experience.list]]
        title = "C# Developer"
        dates = "2009 - 2009"
        company = "Sciencesoft"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."









    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Project Lorem Ipsum"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.projects.list]]
        title = "Project Sed Fringilla"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

        [[params.projects.list]]
        title = "Project Praesent"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."










    [params.information]
        enable = true

        [[params.information.list]]
        title = "Certifications/Courses"
        [[params.information.list.items]]
        details = "2019 路 AWS Certified Cloud Practitioner"
        [[params.information.list.items]]
        details = "2017 路 M101J: MongoDB for Java Developers"
        [[params.information.list.items]]
        details = "2017 路 M001: MongoDB Basics"
        [[params.information.list.items]]
        details = "2014 路 Oracle Certified Associate, Java SE 7 Programmer"

        [[params.information.list]]
        title = "Interests"
        details = "Climbing, Snowboarding, Photography, Travelling"








    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/colinbut"
        title = "Colin But"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/colinbut"
        title = "Colin But"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "//twitter.com/Colin_But"
        title = "@Colin_But"





