# Page settings

baseURL = "http://colinbut.github.io/online-resume/"
languageCode = "en"
title = "Colin But online Resume"
theme = "hugo-devresume-theme"
googleAnalytics = "UA-XXXXXXX-Y"






[params]
    author = "CowboySmall"
    description = "DevResume - Bootstrap 4 Resume/CV Template For Software Developers"


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "Colin But"
        tagline = "DevOps Engineer | AWS"
        avatar = "me_linkedin.png"







    [params.contact]
        enable = true
        location = "London"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:07588818156"
        text = "07588818156"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:colin.but1@hotmail.co.uk"
        text = "colin.but1@hotmail.co.uk"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "http://www.colinbut.com"
        text = "www.colinbut.com"







    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "AWS, Azure, GCP"
        [[params.skills.list.items]]
        details = "Docker/Kubernetes"
        [[params.skills.list.items]]
        details = "Terraform/Cloudformation"
        [[params.skills.list.items]]
        details = "Jenkins CI/CD Pipelines"
        [[params.skills.list.items]]
        details = "Ansible"
        [[params.skills.list.items]]
        details = "Java/Python/JavaScript/React"
        








    [params.education]
        enable = true

        [[params.education.list]]
        degree = "MEng in Computer Science"
        university = "University of Strathclyde, Glasgow"
        dates = "2010 - 2011"
        [[params.education.list]]
        degree = "BSc Computer Science"
        university = "University of Strathclyde, Glasgow"
        dates = "2006 - 2010"








    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"








    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "English"
        level = "Native"
        [[params.languages.list]]
        name = "Chinese (Cantonese)"
        level = "Native"








    [params.interests]
        enable = false

        [[params.interests.list]]
        name = "Football"
        [[params.interests.list]]
        name = "Food"
        [[params.interests.list]]
        name = "Gaming"
        [[params.interests.list]]
        name = "Sightseeing"








    [params.summary]
        enable = true
        text = "A Senior Software/DevOps Engineer who builds, tests, deploys, and runs applications/microservices on the AWS cloud. A strong varied development background in both backend + frontend and with a broad technical experience accumulated to date allowed me to apply my range of technical skills across numerous business domains. A Developer turned DevOps Engineer who is passionate about Infrastructure as Code, creating Pipeline as Code and a firm believer in close collaboration between Developers & Operators aiming to help bridge the gap and shorten the overall release cycle. An effective team member who is very hands-on and takes ownership of business & technical requirements taking them from concept right through to production."








    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "DevOps Engineer"
        dates = "2020 - Present"
        company = "Sainsbury's Digital, Tech & Data"
        [[params.experience.list.items]]
        details = "Infrastructure development using Terraform and Ansible"
        [[params.experience.list.items]]
        details = "Creating CI/CD pipelines with Github Actions & AWS CodeBuild"
        [[params.experience.list.items]]
        details = "Development of a system that allows asynchronous SQL queries to be executed against Snowflake Data Warehouse using AWS native technologies (SAM, API Gateway, Cognito, Lambda, Cloudwatch, X-Ray, DynamoDB, Cloudformation)"
        [[params.experience.list.items]]
        details = "Managing a Cloudera Hadoop based Data Lake Platform"
        [[params.experience.list.items]]
        details = "BAU SysOps Tasks involving AWS services (ACM, Route53, Directory Service, Workspaces, KMS)"
        [[params.experience.list.items]]
        details = "General scripting using Python & Bash"
        [[params.experience.list.items]]
        details = "Experimenting with ChatBots, external API integration with Chat System like Slack"

        [[params.experience.list]]
        title = "DevOps Engineer"
        dates = "2020"
        company = "n/a (Freelance)"
        [[params.experience.list.items]]
        details = "Infrastructure provisioning using Terraform to provision AWS resources"
        [[params.experience.list.items]]
        details = "Automating deployment using Ansible to deploy the application onto AWS cloud platform"
        [[params.experience.list.items]]
        details = "Creating CI/CD Jenkins pipelines using both Declarative & Scripted Syntax based on Groovy DSL"
        [[params.experience.list.items]]
        details = "Developing Jenkins Shared Library in Groovy for encapsulating common pipeline code"
        [[params.experience.list.items]]
        details = "Creating Kubernetes cluster on AWS using AWS's managed Kubernetes Service (EKS)"
        [[params.experience.list.items]]
        details = "Creating Kubernetes definitions in manifests yaml files and applying them"
        [[params.experience.list.items]]
        details = "Working with Kubernetes Package Manager (Helm) to manage applications on Kubernetes"
        [[params.experience.list.items]]
        details = "Full Stack development of web app using React, Java, Spring Boot"

        [[params.experience.list]]
        title = "DevOps Engineer"
        dates = "2019 - 2020"
        company = "Credit Agricole, Corporate & Investment Bank"
        details = "Working in the CVA/CCC team to perform DevOps duties around the bank's core CVA trading applications that peforms trading simulations to manage credit risks of trades. In addition, assisting with the migration of legacy monolithic applications that was running on JBoss/Tomcat application servers/web containers to running on modern infrastructure, i.e. Docker containers operting within the Kubernetes cluster and providing adhoc bug fixes & business feature developments."
        [[params.experience.list.items]]
        details = "Building apps in Docker containers on Kubernetes"
        [[params.experience.list.items]]
        details = "Deployment automation using Ansible, Python"
        [[params.experience.list.items]]
        details = "General workflow automation using Python"
        [[params.experience.list.items]]
        details = "CI/CD pipelines creation in Jenkins using Jenkins Declarative Pipelines"
        [[params.experience.list.items]]
        details = "Continuous Delivery practices proposals"
        [[params.experience.list.items]]
        details = "Implementing Continuous Deployment by automating deployment of built applications from Jenkins CI build server to various Dev/Test servers"
        [[params.experience.list.items]]
        details = "Centralised monitoring using Elastic (ELK) Stack - ElasticSearch, Logstash, Kibana, Beats"
        

        [[params.experience.list]]
        title = "DevOps Engineer"
        dates = "2018 - 2019"
        company = "10x Banking"
        details = "Working on a project in various streams to deliver a backend platform that supports a new challenger bank. Placed within in a horizontal cross-functional feature team to help deliver a particular slice of a larger platform domain. Collaborating with both the Developers & Operators/Infrastructure Engineers in various different teams to help bridge the gap between the two disparate discipline."
        [[params.experience.list.items]]
        details = "Doing Infrastructure as Code: coding Terraform configuration to provision AWS resources"
        [[params.experience.list.items]]
        details = "AWS (EC2, ECS, EKS, ECR, RDS, S3, DynamoDB, Lambda, Cloudformation)"
        [[params.experience.list.items]]
        details = "Actively supporting Java Spring Boot microservices on Kubernetes"
        [[params.experience.list.items]]
        details = "Creating Jenkins 2.0+ CI/CD Pipelines with Jenkinsfile"
        [[params.experience.list.items]]
        details = "API integration with 3rd party services (Companies House, Due Diligence) for ‘onboarding’ a business customer onto 10x’s banking platform"
        [[params.experience.list.items]]
        details = "Doing a PoC for trialling out Consumer-Driven-Contract (CDC) Testing using Pact"
        [[params.experience.list.items]]
        details = "Advanced Routing with a Service Mesh in LinkerD for implemting Blue/Green Deployments"
        [[params.experience.list.items]]
        details = "Experimenting with Kotlin and CockRoachDB for new microservices"
        [[params.experience.list.items]]
        details = "Monitoring cloud-native microservices using SumoLogic"
        [[params.experience.list.items]]
        details = "Application performance metrics measurements monitoring and observation using Prometheus and Grafana"


        [[params.experience.list]]
        title = "Backend Engineer"
        dates = "2016 - 2018"
        company = "Gamesys"
        details = "Working in the Bingo Product Development team to support and maintain an online Bingo game where the whole team was responsible for both the frontend UI development and also providing the backend core bingo gaming engine."
        [[params.experience.list.items]]
        details = "Responsible for creating and running CI build jobs on various CI systems for different apps (Jenkins, Hudson, Bamboo, GoCD)"
        [[params.experience.list.items]]
        details = "Continuous monitoring application using a whole host of monitoring tools (AppDynamnics, ELK stack, Grafana, Splunk, Nagios)"
        [[params.experience.list.items]]
        details = "Actively engaging the tagging of artifacts and liaising with Release Manager in releasing to Production on a bi-weekly release cycle."
        [[params.experience.list.items]]
        details = "Development of a Proof-of-Concept (PoC) on establishing the data model of the bingo scheduling tool backend connecting to a NoSQL MongoDB datastore."
        [[params.experience.list.items]]
        details = "Regular maintenance of database structure & data by writing & executing both Liquibase database migration scripts and adhoc SQL scripts"
        [[params.experience.list.items]]
        details = "Messaging with Google Pub/Sub integrating with Google BigTable, querying with Google BigQuery on GCP"
        [[params.experience.list.items]]
        details = "Worked on backend Bingo Engine built in Java 7, JavaEE, Spring Framework, JMS, DB2, ActiveMQ, JBoss and on a bingo games scheduling tool (Java 8, Spring Boot, JPA, Hibernate, MySQL, MongoDB, ReactJS, Redux, Bootstrap, Jest, Enzyme, Webpack, ES6)"
        

        [[params.experience.list]]
        title = "Backend Engineer"
        dates = "2015 - 2016"
        company = "Solarcentury"
        details = "Working in a small in-house development team developing an online task management & e-commmerce web portal for IKEA which was integrated into thier website. The developed system manages the lifecycles of solar panels from production to sales incl. allowing the public users to purchase solar panels online. Core activities resolved around doing backend Java development with minor frontend work."
        [[params.experience.list.items]]
        details = "Working on backend features development of an online task management & e-commerce web portal."
        [[params.experience.list.items]]
        details = "Occasional frontend work (HTML, CSS, JS, JQuery) on a solar panel calculator tool which is integrated into IKEA's main website."
        [[params.experience.list.items]]
        details = "Help improve the team's agile development process, streamlining it to make it more efficient."

        [[params.experience.list]]
        title = "Software Engineer"
        dates = "2014 - 2015"
        company = "NHS Digital"
        details = "Residing in a project team of 80+ people helping deliver a like-for-like replacement in e-Referral Service (eRS) for the previous NHS online appointment booking system - Choose and Book (CAB). Working on the Data Migration stream. "
        [[params.experience.list.items]]
        details = "Developing & testing the migration of production data from existing system's Oracle RDBMS to new system's PostgreSQL."
        [[params.experience.list.items]]
        details = "Setting up and providing full test environments for data migration testing."
        [[params.experience.list.items]]
        details = "Assisting with functional testing of key systems feature."

        [[params.experience.list]]
        title = "Software Engineer"
        dates = "2014 - 2014"
        company = "NHS Digital"
        details = "Within a 'DevOps' focused project team of 40+ people, assisting with the delivery of NHS Spine II which is a complete-rewrite of NHS's legacy backend integration messaging system (Spine I)."
        [[params.experience.list.items]]
        details = "Application monitoring using monitoring tools like Splunk, observing application performance from charts and graphs."
        [[params.experience.list.items]]
        details = "Non functional testing of failing over key components of the system's architecture like killing Redis sentinel."
        [[params.experience.list.items]]
        details = "Prioritization of automated peformance testing using Grinder (a Java Load Testing tool) with test scripts implemented using Jython (a Java implementation of Python)."

        [[params.experience.list]]
        title = "Software Engineer"
        dates = "2011 - 2014"
        company = "Thomson Reuters"
        details = "Working in a project focused team of 20+ people offsite on Bjss's development centre for Thomson Reuters on their backend New Matching Host (NMH) which is a real-time low latency multithreaded high availability FX trading host system for matching traders deals. From doing operations & infrastructure type tasks in setting up/provisioning bare-metal servers, to fixing defects, non-functional testing, performance testing, administrating databases, implementing in-house utility tools, testing tools, trading tools."
        [[params.experience.list.items]]
        details = "Using Bash Shell Scripting to create scripts that automate deployment of application to on- premise physical bare metal servers."
        [[params.experience.list.items]]
        details = "Deadlock investigations, searching for throughput spikes using low level traditional programming techniques (timing measurements to do code instrumentation, Thread dumps)"
        [[params.experience.list.items]]
        details = "Performance Testing, application & database bottlenecks diagnosis"
        [[params.experience.list.items]]
        details = "Java JVM heap memory, CPU, Threads, Garbage Collection analysis & fine tuning"

        [[params.experience.list]]
        title = "Software Engineer"
        dates = "2011 - 2014"
        company = "Bjss"
        details = "A Software Engineer participating in different projects for multiple clients. Involved throughout the whole Software Development lifecycle (SDLC) which includes development (new features, bug fixes), testing (functional & non-functioanl), operations"

        [[params.experience.list]]
        title = "Web Developer"
        dates = "2010 - 2011"
        company = "Mobile Velocity"
        details = "An initial co-founder of the company where I lead the company's technical development through the initial stages of their journey. I helped developed client side of a mobile web application and actively engaged with a 3rd Party technology consortium (included a former W3C panel member) for a technical feasibility study in developing prototypes using emerging (at the time) HTML5 technology."
        
        [[params.experience.list]]
        title = "C# Developer"
        dates = "2009 - 2009"
        company = "Sciencesoft"
        details = "A summer internship where I was in a small team of three fellow interns to work on an automation test suite for testing the functional features of the company's core suite of products which were a series of different applications that performs modelling for oil and gas energy simulations."









    [params.projects]
        enable = false

        [[params.projects.list]]
        title = "Microservice AWS Demo"
        meta = "Open Source"
        tagline = "A complete demo project containing a collection of smaller individual demo projects that showcases various methods of building a microservice (in any programming language - currently only Java & NodeJs) and running it on the various different AWS compute services (EC2 non-containerized, EC2 with Docker, ECS, ECS Fargate, EKS, Elastic Beanstalk)."

        [[params.projects.list]]
        title = "Snowman"
        meta = "Open Source"
        tagline = "A demo project showing a typical traditional monolithic enterprise scale application. Showcasing numerous features incl. transactions, caching, database migration, scheduling, messaging, Restful web services, database access, enterprise integration, scalability, clustering, high availability, software architecture, enterprise application architecture."

        [[params.projects.list]]
        title = "Sales Order System"
        meta = "Open Source"
        tagline = "Sales Order System is one of my earliest pet project of mine which originally spawn from an idea/application I worked on whilst working for Solarcentury. Project demontrates a very simple full stack Java Spring Boot application using JavaEE technologies in the backend with JSP serving up HTML, CSS, with JS, JQuery on the frontend."










    [params.information]
        enable = true

        [[params.information.list]]
        title = "Certifications/Courses"
        [[params.information.list.items]]
        details = "2020 · Hashicorp Certified: Terraform Associate"
        [[params.information.list.items]]
        details = "2020 · DevOps Engineering on AWS"
        [[params.information.list.items]]
        details = "2019 · AWS Certified Cloud Practitioner"
        [[params.information.list.items]]
        details = "2017 · M101J: MongoDB for Java Developers"
        [[params.information.list.items]]
        details = "2017 · M001: MongoDB Basics"
        [[params.information.list.items]]
        details = "2014 · Oracle Certified Associate, Java SE 7 Programmer"








    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/colinbut"
        title = "Colin But"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/colinbut"
        title = "Colin But"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "//twitter.com/Colin_But"
        title = "@Colin_But"
        [[params.social.list]]
        icon = "fab fa-medium"
        url = "//medium.com/@Colin_But"
        title = "@Colin_But"





